site_name: ClassifAI Engine Documentation
site_url: https://classifai.github.io/classifai-engine/
nav:
  - Home: index.md
  - About: 
    - About: about/about.md
    - Changelog: about/changelog.md
    - Configuration: configuration.md
  - Installation: installation.md
  - 'Getting Started': developer.md
  - 'API Reference':
    - 'API Reference': api/api.md
    - Analysis: api/api_analyze.md
  - 'Contribution':
    - Contribute: contribution/contributing.md
    - Edit the Docs: contribution/editing_docs.md
    - 'Style Guide': contribution/style_guide.md
    - 'Pre-Commit Hooks': contribution/instructions_for_pre-commit.md
  - 'Project Structure': structure.md
  - 'Transcription Model Information': transcription.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    code: Roboto Mono
  logo: assets/gears.png
  favicon: assets/gears.png
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TCU-Instructional-AI/classifAI-engine
copyright: Copyright &copy; 2023 ClassifAI
repo_url: https://github.com/TCU-Instructional-AI/classifAI-engine
repo_name: ClassifAI-engine
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python: 
        paths: [.]


