site_name: ClassifAI Engine Documentation
site_url: https://classifai.github.io/classifai-engine/
nav:
  - Home: index.md
  - About: about.md
  - 'Contribution':
    - Edit the Docs: contribution/editing_docs.md
    - Contribute Code: contribution/contributing.md
    - 'Style Guide': contribution/style_guide.md
    - 'Pre-Commit Hooks': contribution/instructions_for_pre-commit.md
  - 'API Reference': api.md
  - 'Project Structure': structure.md
  - 'Changelog': changelog.md
  - 'Transcription Model Information': transcription.md
theme:
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  font:
    code: Roboto Mono
  logo: assets/gears.png
  favicon: assets/gears.png
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TCU-Instructional-AI/classifAI-engine
copyright: Copyright &copy; 2023 ClassifAI
repo_url: https://github.com/TCU-Instructional-AI/classifAI-engine
repo_name: ClassifAI-engine
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

